language: go
matrix:
  include:
    - go: 1.4
      env: TOOLS_CMD=golang.org/x/tools/cmd

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

install:
 - export GOPATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH
 - export PATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH
 - go get ${TOOLS_CMD}/cover
 - go get ${TOOLS_CMD}/vet

script:
 - ./test

notifications:
  email: false
