#!/bin/bash -e

ORG_PATH="github.com/paz-sh"
REPO_PATH="${ORG_PATH}/paz.sh"

if [ ! -h gopath/src/${REPO_PATH} ]; then
  mkdir -p gopath/src/${ORG_PATH}
  ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath

eval $(go env)

echo "Building pazctl"
CGO_ENABLED=0 go build -o bin/paz -a -ldflags '-s' ${REPO_PATH}/cli
