#!/bin/bash -e

ORG_PATH="github.com/paz-sh"
REPO_PATH="${ORG_PATH}/paz.sh"

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/Godeps/_workspace

if [ ! -h $GOPATH/src/${REPO_PATH} ]; then
  mkdir -p $GOPATH/src/${ORG_PATH}
  ln -s ../../../../../ $GOPATH/src/${REPO_PATH} || exit 255
fi

eval $(go env)

echo "Building pazctl"
CGO_ENABLED=0 go build -o bin/paz -a -ldflags '-s' ${REPO_PATH}/cli
